import type { Metadata } from "next";
import { Yanone_Kaffeesatz } from "next/font/google";
import '@/style/global.scss'

const yanoneKaffeesatz = Yanone_Kaffeesatz({
	weight: '400',
	subsets: ['cyrillic'],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};
// https://api.nasa.gov/planetary/apod?api_key=IMagFQbztvpFQTD959rak7sdAcXH9EfZ5qkzo9bB&start_date=2024-01-01&end_date=2024-01-10
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${yanoneKaffeesatz.className}`}>
				<div className="bg">
					
				</div>
				{children}
			</body>
		</html>
	);
}
